### ISSUE TITLE
runIde Just Spinning on Raku Project Open

### ISSUE THREAD

**Issue by librasteve** [ab5tract/comma-plugin#2]
IntelliJ IDEA 2024.2.1 (Ultimate Edition)
macos 14.6.1 sonoma aarch64 (M1)

---

build plugin - success

restart IntelliJ
install comma2.0-zip from disk
assign raku SDK 2024.08

new project > raku ...ok
close / open project ... ok (change .t to .rakutest)

open existing small comma project (with old .idea files)
... updating indexes ... fail ... force quit

rm -rf .idea
rm *.iml

same
open cleaned small comma project (with no .idea files)
... updating indexes ... fail ... force quit

---

build plugin - success
runIde - some warnings, but vm instance is running

10:42:03: Executing 'runIde'...

Starting Gradle Daemon...
Gradle Daemon started in 552 ms
> Task :initializeIntellijPlatformPlugin
> Task :patchPluginXml UP-TO-DATE
> Task :generateManifest UP-TO-DATE
> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :compileKotlin UP-TO-DATE
> Task :verifyPluginProjectConfiguration UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :instrumentedJar UP-TO-DATE
> Task :composedJar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE

> Task :runIde
WARN: `include` is supported only on a root level ([row,col,system-id]: [40,5,"/Users/stephenroe/Library/CloudStorage/Dropbox/GitWorld/comma-plugin/build/idea-sandbox/IC-2024.2/plugins/comma/lib/comma-2.0.jar"])
WARN: `include` is supported only on a root level ([row,col,system-id]: [40,5,"/Users/stephenroe/Library/CloudStorage/Dropbox/GitWorld/comma-plugin/build/idea-sandbox/IC-2024.2/plugins/comma/lib/comma-2.0.jar"])
2024-09-16 10:42:11,435 [    697]   WARN - #c.i.o.a.Application - No URL bundle (CFBundleURLTypes) is defined in the main bundle.
To be able to open external links, specify protocols in the app layout section of the build file.
Example: args.urlSchemes = ["your-protocol"] will handle following links: your-protocol://open?file=file&line=line
2024-09-16 10:42:11,542 [    804]   WARN - c.i.o.u.r.overrides - Conflicting registry key definition for key kotlin.mpp.tests.force.gradle: it was defined by plugin org.jetbrains.kotlin but redefined by plugin org.jetbrains.kotlin. Consider adding overrides="true" for one of the plugins, see the documentation for com.intellij.openapi.util.registry.RegistryKeyBean.overrides for more details.
2024-09-16 10:42:11,781 [   1043]   WARN - #c.i.i.s.p.i.BundledSharedIndexProvider - Bundled shared index is not found at: /Users/stephenroe/.gradle/caches/transforms-3/435c17ab808b478c5db4cfe34595852c/transformed/ideaIC-2024.2-aarch64/jdk-shared-indexes
2024-09-16 10:42:11,784 [   1046]   WARN - #c.i.u.n.s.ConfirmingTrustManager - Received an empty list of custom trusted root certificates from the system. Check log above for possible errors, enable debug logging in category 'org.jetbrains.nativecerts' for more information

---

open same clean small raku project in vm

more warnings in master window...

2024-09-16 10:43:43,450 [  92712]   WARN - #c.i.s.ComponentManagerImpl - `preload=NOT_HEADLESS` must be used only for core services (service=org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService, plugin=org.jetbrains.kotlin)
2024-09-16 10:43:43,450 [  92712]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=org.jetbrains.idea.maven.project.MavenProjectsManagerEx, plugin=org.jetbrains.idea.maven)
2024-09-16 10:43:43,450 [  92712]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=org.jetbrains.idea.maven.navigator.MavenProjectsNavigator, plugin=org.jetbrains.idea.maven)
2024-09-16 10:43:43,450 [  92712]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=org.jetbrains.idea.maven.tasks.MavenShortcutsManager, plugin=org.jetbrains.idea.maven)
2024-09-16 10:43:43,450 [  92712]   WARN - #c.i.s.ComponentManagerImpl - `preload=NOT_HEADLESS` must be used only for core services (service=com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,450 [  92712]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.users.BackendUserManager, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.ports.CwmPortForwardingToolWindowManager, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.users.BackendCWMUserFocusHost, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.FollowMeManagerService, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.BackendProjectViewSync, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.BackendFollowMeEditorsHost, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.BackendFollowMeDebuggerHost, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:43,451 [  92713]   WARN - #c.i.s.ComponentManagerImpl - `preload=TRUE` must be used only for core services (service=com.intellij.cwm.plugin.following.FollowMeLookupSynchronizer, plugin=com.jetbrains.codeWithMe)
2024-09-16 10:43:48,962 [  98224]   WARN - #c.i.d.MemorySizeConfigurator - The IDE is not configured for using custom VM options (jb.vmOptionsFile=null)
java.io.IOException: The IDE is not configured for using custom VM options (jb.vmOptionsFile=null)
	at com.intellij.diagnostic.VMOptions.setOptions(VMOptions.java:202)
	at com.intellij.diagnostic.VMOptions.setOption(VMOptions.java:193)
	at com.intellij.diagnostic.VMOptions.setOption(VMOptions.java:175)
	at com.intellij.diagnostic.MemorySizeConfigurator.execute(MemorySizeConfigurator.kt:54)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:496)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

**Comment by ab5tract** [comment]
Unfortunately the only solution I've found for this so far is to use `New Project from Existing Sources...` instead of `Open`.

I've edited `README.md` to inform the user about this.

Still, it blows my mind a bit that `rm -rf .idea` doesn't work, but nuking `.idea` via the `New Project from Existing Sources...` action doesn't work.

I have a feeling it's related to the 100% deprecated, unsupported use of `OpenProjectTask` in `RakuProjectOpenProcessor`.

**Comment by ab5tract** [comment]
This should be fixed as of #6c73c88258f7479ff6f223602f8bd2636526e198

It essentially does the same thing as `New Project from Existing Sources...` (eg, nuking the old `.idea` directory as well as the now-useless-anyway `$project.iml` file) -- but automatically and in the background.

**Comment by librasteve** [comment]
confirm this is fixed
