### ISSUE TITLE
Running Cro services as IntelliJ services

### ISSUE THREAD

**Issue by ab5tract** [ab5tract/comma-plugin#27]
Make sure that Cro can be run as a service inside of IDEA.

**Comment by ikarpenis** [comment]
The installation of the new comma version gave me the following error:

> `com.intellij.diagnostic.PluginException: Cannot create extension (class=cro.org.raku.comma.CroTemplateCall) [Plugin: org.raku.comma]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:989)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:73)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:33)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.kt:403)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.createExtensionInstances(ExtensionPointImpl.kt:361)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.kt:222)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.kt:237)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.kt:51)
	at org.raku.comma.structureView.RakuStructureViewElement.getChildren(RakuStructureViewElement.java:46)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:209)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:43)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:35)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:893)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:424)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:332)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:326)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:348)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.computeNode(AsyncTreeModel.java:668)
	at com.intellij.ui.tree.AsyncTreeModel$Command.computeNode(AsyncTreeModel.java:541)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:361)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.run(CoroutineInvokerDelegate.kt:38)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:189)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:173)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:470)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.offer$lambda$2(CoroutineInvokerDelegate.kt:27)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1.invokeSuspend$lambda$1$lambda$0(CoroutineInvokerDelegate.kt:97)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate.withProperContext$lambda$0(CoroutineInvokerDelegate.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate.withProperContext(CoroutineInvokerDelegate.kt:72)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1.invokeSuspend(CoroutineInvokerDelegate.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.ClassNotFoundException: cro.org.raku.comma.CroTemplateCall PluginClassLoader(plugin=PluginDescriptor(name=Comma for Raku, id=org.raku.comma, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IdeaIC2024.3/comma, version=2.0, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/IntelliJ/idea-IC-242.22855.74/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/IntelliJ/idea-IC-242.22855.74/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/IntelliJ/idea-IC-242.22855.74/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/IntelliJ/idea-IC-242.22855.74/lib, version=243.21565.193, package=null, isBundled=true), )
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1462)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass$default(ComponentManagerImpl.kt:1458)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:896)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:21)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
	... 59 more
`

**Comment by ikarpenis** [comment]
![image](https://github.com/user-attachments/assets/d34cfcad-b933-4568-b2aa-fc3ee9667970)

**Comment by ab5tract** [comment]
Hi @ikarpenis , were you doing anything of note at the time when this happened?

**Comment by ikarpenis** [comment]
Hi there! No. Not a thing. In fact this message came out right after the installation of the plugin!

**Comment by ab5tract** [comment]
Ok good to know. Is it firing constantly or was that the only time?

Also, the installation should prompt for a restart. Did it happen after the restart? Or was it triggered immediately?

**Comment by ikarpenis** [comment]
The message shows up every time IntelliJ is starting. Otherwise the IDE is working fine!
